version: '3.8'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  axelor-app:
    image: kapsiki/kapsiki-axelor:latest
    container_name: axelor-app
    depends_on:
      - db
    environment:
      AXELOR_CONFIG_DB_DEFAULT_URL: jdbc:postgresql://db:5432/axelor
      AXELOR_CONFIG_DB_DEFAULT_USER: axelor
      AXELOR_CONFIG_DB_DEFAULT_PASSWORD: axelor
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    
