version: '3.3'

services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  axelor:
    image: kapsiki/kapsiki-erp:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgresql_data:
