version: '3.3'

services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    restart: unless-stopped
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "axelor"]
      interval: 10s
      timeout: 5s
      retries: 5

  axelor:
    image: kapsiki/kapsiki-erp:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_NAME: axelor
      DB_USER: axelor
      DB_PASSWORD: axelor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgresql_data:
