version: '3'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: axelor
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: password
    volumes:
      - /home/axelor/axelor-db/pgdata:/var/lib/postgresql/data
    networks:
      - axelor-network

  axelor:
    image: kapsiki/kapsiki-axelor:latest
    build: .
    ports:
      - "80:80"       
      - "443:443"     
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=axelor
      - DB_USER=axelor
      - DB_PASSWORD=password
    volumes:
      - ./certs:/etc/nginx/certs:ro             
      - ./volumes/var/lib/tomcat:/var/lib/tomcat       
      - ./volumes/var/log/tomcat:/var/log/tomcat        
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - axelor-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G


networks:
  axelor-network:
    driver: bridge
